[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff]
# Same as flake8's max-line-length
line-length = 88

[tool.ruff.lint]
# Extend the default ignore list with flake8's ignored rules
extend-ignore = ["E203"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]